# 第三章证明正确性

短语“证明正确性”通常用在计算准确性的上下文中，但是关于单元测试，证明正确性实际上有三大类，只有第二类与计算本身有关:

*   验证计算的输入是否正确(方法契约)。
*   验证一个方法调用产生了期望的计算结果(称为计算方面)，分为四个典型的过程:

*   数据转换
*   数据整理
*   状态变换
*   状态正确性

*   外部错误处理和恢复。

在应用程序的许多方面，单元测试通常不能用于证明正确性。这些包括大多数用户界面特性，如布局和可用性。在许多情况下，单元测试不是测试性能、负载等方面的需求和应用程序行为的合适技术。

## 单元测试如何证明正确性

证明正确性包括:

*   核实合同。
*   验证计算结果。
*   验证数据转换结果。
*   验证是否正确处理了外部错误。

让我们看看这些类别的一些例子，它们的优点、缺点以及我们在代码中可能遇到的问题。

### 证明合同已执行

单元测试最基本的形式是验证开发人员已经编写了一个方法，该方法清楚地陈述了调用者和被调用方法之间的“契约”。这通常采取验证方法的错误输入导致异常被抛出的形式。例如，如果分母为 0，则“除以”方法可能会抛出`ArgumentOutOfRangeException`:

```cs
    public static int Divide(int numerator, int denominator)
    {
      if (denominator == 0)
      {
        throw new ArgumentOutOfRangeException("Denominator cannot be 0.");
      }

      return numerator / denominator;
    }

    [TestMethod]
    [ExpectedException(typeof(ArgumentOutOfRangeException))]
    public void BadParameterTest()
    {
      Divide(5, 0);
    }

```

然而，验证一个方法实现契约测试是一个人能写的最弱的单元测试之一。

### 证明计算结果

更强的单元测试包括验证计算是否正确。将您的方法归类为三种计算形式之一是很有用的:

*   数据整理
*   数据转换
*   状态变换

这些决定了您可能想要为特定方法编写的单元测试的种类。

#### 数据整理

上一个样本中的`Divide`方法可以认为是一种数据约简的形式。它接受两个值并返回一个值。为了说明:

```cs
    [TestMethod]
    public void VerifyDivisionTest()
    {
      Assert.IsTrue(Divide(6, 2) == 3, "6/2 should equal 3!");
    }

```

这说明了测试一种通常将输入减少到一个结果输出的方法。这是有用的单元测试的最简单形式。

#### 数据转换

数据转换单元测试倾向于对值集进行操作。例如，以下是对将笛卡尔坐标转换为极坐标的方法的测试。

```cs
    public static double[] ConvertToPolarCoordinates(double x, double y)
    {
      double dist = Math.Sqrt(x * x + y * y);
      double angle = Math.Atan2(y, x);

      return new double[] { dist, angle };
    }

    [TestMethod]
    public void ConvertToPolarCoordinatesTest()
    {
      double[] pcoord = ConvertToPolarCoordinates(3, 4);
      Assert.IsTrue(pcoord[0] == 5, "Expected distance to equal 5");
      Assert.IsTrue(pcoord[1] == 0.92729521800161219, "Expected angle to be 53.130
          degrees");
    }

```

该测试验证了数学变换的正确性。

##### 列表转换

列表转换应该分为两个测试:

*   验证核心转换是否正确。
*   验证列表操作是否正确。

例如，从单元测试的角度来看，以下示例编写得很差，因为它同时包含了数据简化和数据转换:

```cs
    public struct Name
    {
      public string FirstName { get; set; }
      public string LastName { get; set; }
    }

    public List<string> ConcatNames(List<Name> names)
    {
      List<string> concatenatedNames = new List<string>();

      foreach (Name name in names)
      {
        concatenatedNames.Add(name.LastName + ", " + name.FirstName);
      }

      return concatenatedNames;
    }

    [TestMethod]
    public void NameConcatenationTest()
    {
      List<Name> names = new List<Name>()
      {
        new Name() { FirstName="John", LastName="Travolta"},
        new Name() {FirstName="Allen", LastName="Nancy"}
      };

      List<string> newNames = ConcatNames(names);

      Assert.IsTrue(newNames[0] == "Travolta, John");
      Assert.IsTrue(newNames[1] == "Nancy, Allen");
    }

```

通过将数据简化与数据转换分开，可以更好地对这段代码进行单元测试:

```cs
    public string Concat(Name name)
    {
      return name.LastName + ", " + name.FirstName;
    }

    [TestMethod]
    public void ContactNameTest()
    {
      Name name = new Name() { FirstName="John", LastName="Travolta"};
      string concatenatedName = Concat(name);
      Assert.IsTrue(concatenatedName == "Travolta, John");
    }

```

##### λ表达式和单元测试

语言集成查询(LINQ)语法与 lambda 表达式紧密结合，从而产生易于阅读的语法，这使得单元测试变得困难。例如，这段代码:

```cs
    public List<string> ConcatNamesWithLinq(List<Name> names)
    {
      return names.Select(t => t.LastName + ", " + t.FirstName).ToList();
    }

```

比前面的例子要优雅得多，但是它并不适合单元测试实际的“单元”，也就是说，从名称结构到 lambda 函数`t => t.LastName + ", " + t.FirstName`中表达的单个逗号分隔字符串的数据简化。要从列表操作中分离单元，需要:

```cs
    public List<string> ConcatNamesWithLinq(List<Name> names)
    {
      return names.Select(t => Concat(t)).ToList();
    }

```

我们可以看到，单元测试经常需要重构代码，以将单元与其他转换分开。

#### 状态变换

大多数语言都是“有状态的”，类通常管理状态。一个类的状态，由它的属性来表示，通常是一个有用的测试。考虑这个表示连接概念的类:

```cs
    public class AlreadyConnectedToServiceException : ApplicationException
    {
      public AlreadyConnectedToServiceException(string msg) : base(msg) { }
    }

    public class ServiceConnection
    {
      public bool Connected { get; protected set; }

      public void Connect()
      {
        if (Connected)
        {
          throw new AlreadyConnectedToServiceException("Only one connection at a time is permitted.");
        }

        // Connect to the service.
        Connected = true;
      }

      public void Disconnect()
      {
        // Disconnect from the service.
        Connected = false;
      }
    }

```

我们可以编写单元测试来验证对象的各种允许和不允许的状态:

```cs
    [TestClass]
    public class ServiceConnectionFixture
    {
      [TestMethod]
      public void TestInitialState()
      {
        ServiceConnection conn = new ServiceConnection();
        Assert.IsFalse(conn.Connected);
      }

      [TestMethod]
      public void TestConnectedState()
      {
        ServiceConnection conn = new ServiceConnection();
        conn.Connect();
        Assert.IsTrue(conn.Connected);
      }

      [TestMethod]
      public void TestDisconnectedState()
      {
        ServiceConnection conn = new ServiceConnection();
        conn.Connect();
        conn.Disconnect();
        Assert.IsFalse(conn.Connected);
      }

      [TestMethod]
      [ExpectedException(typeof(AlreadyConnectedToServiceException))]
      public void TestAlreadyConnectedException()
      {
        ServiceConnection conn = new ServiceConnection();
        conn.Connect();
        conn.Connect();
      }
    }

```

这里，每个测试都验证对象状态的正确性:

*   当它被初始化时。
*   当指示连接到服务时。
*   当指示断开服务时。
*   当尝试多个同时连接时。

状态验证经常揭示状态管理中的缺陷。另请参见下面的“[嘲讽类](#_Mocking_Classes)”以获得对前面示例代码的进一步改进。

### 证明方法正确处理外部异常

外部错误处理和恢复通常比测试您自己的代码是否在正确的时间生成异常更重要。这有几个原因:

*   您无法控制物理上独立的依赖项，无论它是 web 服务、数据库还是其他独立的服务器。
*   您无法证明他人代码的正确性，通常是第三方库。
*   第三方服务和软件可能会抛出一个异常，因为您的代码正在创建但没有检测到一个问题(并且不一定容易检测到)。例如，当删除数据库中的记录时，数据库会引发异常，因为其他表中的记录引用了您的程序正在删除的记录，从而违反了外键约束。

这类异常很难测试，因为它们至少需要创建一些错误，而这些错误通常是由您无法控制的服务生成的。一种方法是“模仿”服务；但是，这只有在外部对象用接口、抽象类或虚拟方法实现的情况下才有可能。

#### 嘲讽类

例如，“ServiceConnection”类的早期代码是不可模仿的。如果您想要测试它的状态管理，您必须在物理上创建一个到服务(无论是什么)的连接，该连接在运行单元测试时可能可用，也可能不可用。更好的实现可能如下所示:

```cs
    public class MockableServiceConnection
    {
      public bool Connected { get; protected set; }

      protected virtual void ConnectToService()
      {
        // Connect to the service.
      }

      protected virtual void DisconnectFromService()
      {
        // Disconnect from the service.
      }

      public void Connect()
      {
        if (Connected)
        {
          throw new AlreadyConnectedToServiceException("Only one connection at a time is permitted.");
        }

        ConnectToService();
        Connected = true;
      }

      public void Disconnect()
      {
        DisconnectFromService();
        Connected = false;
      }
    }

```

请注意，这个小的重构现在允许您编写一个模拟类:

```cs
    public class ServiceConnectionMock : MockableServiceConnection
    {
      protected override void ConnectToService()
      {
        // Do nothing.
      }

      protected override void DisconnectFromService()
      {
        // Do nothing.
      }
    }

```

这允许您编写一个单元测试来测试状态管理，而不管服务的可用性如何。正如这个例子所说明的，即使是简单的架构或实现更改也可以极大地提高类的可测试性。

### 证明一个 Bug 是可重造的

讽刺的是，你证明问题已经得到纠正的第一道防线就是证明问题存在。前面我们看到了一个编写测试的例子，证明了 Divide 方法检查分母值`0`。假设因为用户在输入分母值`0`时崩溃了程序，所以提交了错误报告。

#### 阴性测试

首要任务是创建一个测试来测试这种情况:

```cs
    [TestMethod]
    [ExpectedException(typeof(DivideByZeroException))]
    public void BadParameterTest()
    {
      Divide(5, 0);
    }

```

这个测试*通过了*，因为我们通过验证当分母为`0`时，会产生一个`DivideByZeroException`来证明这个 bug 存在。这类测试被认为是“阴性测试”，因为当出现错误时，它们*会通过*。阴性测试和阳性测试一样重要(下面讨论)，因为它在问题被纠正之前验证问题的存在。

### 证明 Bug 已修复

显然，我们想证明一个 bug 已经被修复了。这是一个“阳性”测试。

#### 阳性检测

我们现在可以引入一个新的测试，这个测试将测试代码本身通过抛出`ArgumentOutOfRangeException`来检测错误。

```cs
    [TestMethod]
    [ExpectedException(typeof(ArgumentOutOfRangeException))]
    public void BadParameterTest()
    {
      Divide(5, 0);
    }

```

如果我们能在修复问题之前编写这个测试*，我们会看到测试失败。最后，修复问题后，我们的阳性测试通过，阴性测试现在失败。*

虽然这是一个微不足道的例子，但它展示了两个概念:

*   阴性测试——证明某些东西反复不起作用——对于理解问题和解决方案很重要。
*   积极的测试——证明问题已经解决——不仅对验证解决方案很重要，而且对每次进行更改时重复测试也很重要。单元测试在回归测试中扮演着重要的角色。

最后，证明 bug 存在并不总是容易的。然而，作为一般的经验法则，需要太多设置和嘲讽的单元测试表明被测试的代码没有与外部依赖足够隔离，并且可能是重构的候选对象。

### 证明更改代码时没有损坏

很明显，回归测试是单元测试的一个有用的结果。当代码经历变化时，如果您在单元测试中有良好的代码覆盖率，就会出现 bug。这有效地节省了大量的调试时间，更重要的是，当程序员而不是用户发现错误时，节省了时间和金钱。

### 证明满足要求

应用程序开发通常从一组高级需求开始，通常围绕用户界面、工作流和计算。理想情况下，团队将*可见的*需求集合简化为一组编程需求，这些需求本质上是用户不可见的*。*

 *区别体现在程序是如何测试的。集成测试通常是在*可见的*级别，而单元测试是在*不可见的*更细微的地方，编程正确性测试。重要的是要记住，单元测试并不是为了取代集成测试；但是，正如高级应用程序需求一样，也有可以定义的低级编程需求。由于这些编程需求，编写单元测试非常重要。

让我们采取一种圆的方法。那个。NET 数学。Round 方法将向上舍入分数部分大于 0.5 的数字，但当分数部分小于或等于 0.5 时，将向下舍入。假设这不是我们想要的行为(无论出于什么原因)，当分数部分为 0.5 或更大时，我们想要取整。这是一个计算需求，应该能够从更高级别的集成需求中导出，从而产生以下方法和测试:

```cs
    public static int RoundUpHalf(double n)
    {
      if (n < 0) throw new ArgumentOutOfRangeException("Value must be >= 0.");

      int ret = (int)n;
      double fraction = n - ret;

      if (fraction >= 0.5)
      {
        ++ret;
      }

      return ret;
    }

    [TestMethod]
    public void RoundUpTest()
    {
      int result1 = RoundUpHalf(1.5);
      int result2 = RoundUpHalf(1.499999);
      Assert.IsTrue(result1 == 2, "Expected 2.");
      Assert.IsTrue(result2 == 1, "Expected 1.");
    }

```

还应该为异常编写一个单独的测试。

采用通过集成测试验证的应用程序级需求，并将其降低到较低级别的计算需求，是整个单元测试策略的重要部分，因为它定义了应用程序必须满足的明确计算需求。如果这个过程遇到困难，尝试将应用程序需求转换为三个计算类别之一:数据缩减、数据转换和状态更改。*